/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117374-gf339169f35-20241006"
#endif /* AVUTIL_FFVERSION_H */
